# Generated by Django 5.1.4 on 2024-12-10 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                (
                    "route_of_administration",
                    models.CharField(
                        choices=[
                            ("oral", "Orally"),
                            ("parentral/im", "Intra-muscular"),
                            ("parentral/iv", "Intravenous"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "dosage_unit_of_measure",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("gravimetric/mg", "Milligram/mg"),
                            ("volumetric/ml", "Milliliter/ml"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                ("dosage_quantity_of_units_per_time", models.FloatField(null=True)),
                ("dosage_frequency", models.PositiveIntegerField(null=True)),
                (
                    "periodic_interval",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Regimen"),
                            ("weekly", "Weekly Regimen"),
                            ("monthly", "Monthly Regimen"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "first_time_of_intake",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("stopped_by_datetime", models.DateTimeField(blank=True, null=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("drug_interaction_severity", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
